---
name: Hello
on:
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      # - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      # - locked
      - unlocked
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
jobs:
  hello:
    name: Hello
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Triggered by ${{ github.event_name }} event, workflow ${{ github.workflow }}, run_id ${{ github.run_id }}, event sha ${{ github.event.pull_request.head.sha }}"
      - run: sleep 5
