---
name: Hello
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
jobs:
  hello:
    name: Hello
    runs-on: ubuntu-20.04
    steps:
      - name: Print
      - run: echo "Triggered by ${{ github.event_name }} event, workflow: ${{ github.workflow }}, run_id: ${{ github.run_id }}"
